In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("dataset_Facebook.csv",sep=";")

In [6]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [7]:
df.shape

(500, 19)

In [8]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [9]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [10]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [12]:
df["Paid"].fillna(df["Paid"].mode(),inplace=True)
df["like"].fillna(df["like"].mean(),inplace=True)
df["share"].fillna(df["share"].mean(),inplace=True)

C:\Users\abhis\AppData\Local\Temp\ipykernel_676\929039197.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Paid"].fillna(df["Paid"].mode(),inplace=True)
C:\Users\abhis\AppData\Local\Temp\ipykernel_676\929039197.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["like"].fillna(df["like"].mean(),inplace=True)
C:\Users\abhis\AppData\Local\Temp\ipykernel_676\929039197.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["share"].fillna(df["share"].mean(),inplace=True)

In [13]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [17]:
subset1=df[df["Category"]==2]
subset1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,91758,Photo,2,2,5,3,1.0,15880,51571,1188,1071,1410,47976,13560,677,1,200.0,37.0,238
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [18]:
subset2=df[["Type","Post Month","Post Weekday","Post Hour","Total Interactions"]]
subset2

       Type  Post Month  Post Weekday  Post Hour  Total Interactions
0     Photo          12             4          3                 100
1    Status          12             3         10                 164
2     Photo          12             3          3                  80
3     Photo          12             2         10                1777
4     Photo          12             2          3                 393
..      ...         ...           ...        ...                 ...
495   Photo           1             7          2                  84
496   Photo           1             5          8                  75
497   Photo           1             5          2                 115
498   Photo           1             4         11                 136
499   Photo           1             4          4                 119

[500 rows x 5 columns]

In [22]:
subset3=df[df["Page total likes"]>91758]
subset3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,92293,Photo,3,2,7,13,1.0,10040,17029,1429,1346,2022,11744,6964,742,19,214.0,78.0,311
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.0,176
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
465,91972,Photo,3,2,6,3,0.0,6484,10832,1166,1115,1441,7316,4280,583,4,128.0,38.0,170
466,91865,Photo,2,2,5,13,1.0,4840,7466,949,923,1116,5362,3370,447,3,47.0,21.0,71

In [23]:
subset4=df[:100]
subset4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,137059,Photo,3,10,6,10,0.0,3090,5744,391,257,360,3521,1796,293,5,153.0,27.0,185
96,137059,Photo,1,10,6,3,0.0,1101,2548,324,287,2418,1284,704,220,3,51.0,11.0,65
97,137059,Photo,2,10,5,11,0.0,2819,5230,318,218,303,3128,1622,240,1,115.0,26.0,142
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
99,137020,Photo,1,10,4,10,0.0,12776,21893,785,539,881,13272,7800,575,12,328.0,90.0,430

In [24]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [25]:
subset5=df[["comment","like","share","Total Interactions","Type"]]
subset5

     comment    like  share  Total Interactions    Type
0          4    79.0   17.0                 100   Photo
1          5   130.0   29.0                 164  Status
2          0    66.0   14.0                  80   Photo
3         58  1572.0  147.0                1777   Photo
4         19   325.0   49.0                 393   Photo
..       ...     ...    ...                 ...     ...
495        5    53.0   26.0                  84   Photo
496        0    53.0   22.0                  75   Photo
497        4    93.0   18.0                 115   Photo
498        7    91.0   38.0                 136   Photo
499        0    91.0   28.0                 119   Photo

[500 rows x 5 columns]

In [26]:
subset6=df[df["Lifetime Post Consumptions"]<=795]
subset6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [27]:
subset7=df[df["Type"]=="Photo"]
subset7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [28]:
mg=subset2.merge(subset5,how='inner')
mg

,Type,Post Month,Post Weekday,Post Hour,Total Interactions,comment,like,share
0,Photo,12,4,3,100,4,79.0,17.0
1,Photo,12,4,3,100,16,76.0,8.0
2,Photo,12,4,3,100,4,77.0,19.0
3,Photo,12,4,3,100,3,87.0,10.0
4,Status,12,3,10,164,5,130.0,29.0
...,...,...,...,...,...,...,...,...
1041,Photo,1,4,11,136,7,91.0,38.0
1042,Photo,1,4,4,119,19,77.0,23.0
1043,Photo,1,4,4,119,7,84.0,28.0
1044,Photo,1,4,4,119,2,102.0,15.0
1045,Photo,1,4,4,119,0,91.0,28.0

In [29]:
mg.shape

(1046, 8)

In [30]:
subset2.shape

(500, 5)

In [31]:
subset5.shape

(500, 5)

In [33]:
s1 = df.iloc[0:3, 0:3] 
s1

   Page total likes    Type  Category
0            139441   Photo         2
1            139441  Status         2
2            139441   Photo         3

In [34]:
s2=df.iloc[0:3,1:5]
s2

     Type  Category  Post Month  Post Weekday
0   Photo         2          12             4
1  Status         2          12             3
2   Photo         3          12             3

In [35]:
mr=s1.merge(s2,how="inner")

In [36]:
mr

   Page total likes    Type  Category  Post Month  Post Weekday
0            139441   Photo         2          12             4
1            139441  Status         2          12             3
2            139441   Photo         3          12             3

In [37]:
mr.shape

(3, 5)

In [46]:
part1 = df.iloc[:, :5]
part1

     Page total likes    Type  Category  Post Month  Post Weekday
0              139441   Photo         2          12             4
1              139441  Status         2          12             3
2              139441   Photo         3          12             3
3              139441   Photo         2          12             2
4              139441   Photo         2          12             2
..                ...     ...       ...         ...           ...
495             85093   Photo         3           1             7
496             81370   Photo         2           1             5
497             81370   Photo         1           1             5
498             81370   Photo         3           1             4
499             81370   Photo         2           1             4

[500 rows x 5 columns]

In [48]:
part2 = df.iloc[:, 5:10]
part2

,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users
0,3,0.0,2752,5091,178
1,10,0.0,10460,19057,1457
2,3,0.0,2413,4373,177
3,10,1.0,50128,87991,2211
4,3,0.0,7244,13594,671
...,...,...,...,...,...
495,2,0.0,4684,7536,733
496,8,0.0,3480,6229,537
497,2,0.0,3778,7216,625
498,11,0.0,4156,7564,626
499,4,NaN,4188,7292,564

In [50]:
col_merge = pd.concat([part1, part2], axis=1)
col_merge

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users
0,139441,Photo,2,12,4,3,0.0,2752,5091,178
1,139441,Status,2,12,3,10,0.0,10460,19057,1457
2,139441,Photo,3,12,3,3,0.0,2413,4373,177
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211
4,139441,Photo,2,12,2,3,0.0,7244,13594,671
...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733
496,81370,Photo,2,1,5,8,0.0,3480,6229,537
497,81370,Photo,1,1,5,2,0.0,3778,7216,625
498,81370,Photo,3,1,4,11,0.0,4156,7564,626
499,81370,Photo,2,1,4,4,NaN,4188,7292,564

In [40]:
row1 = df.iloc[:100]
row1.shape

(100, 19)

In [41]:
row2 = df.iloc[100:200]
row2.shape

(100, 19)

In [44]:
row_merge = pd.concat([row1, row2], axis=0)
row_merge

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,133594,Photo,2,8,6,10,0.0,5282,8730,703,530,772,5123,3244,470,9,278.0,43.0,330
196,133594,Photo,1,8,6,8,0.0,1809,3130,399,359,494,2541,1435,289,2,64.0,7.0,73
197,133594,Photo,2,8,5,13,0.0,1920,3124,365,331,428,2541,1519,251,1,52.0,7.0,60
198,133451,Photo,1,8,4,9,1.0,1954,3530,356,333,443,3295,1772,252,0,30.0,2.0,32
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290

In [57]:
pvt_table = df.pivot_table(
        values='Lifetime Post Total Reach',
        index='Type',
        columns='Paid',
        aggfunc='mean'
)

In [58]:
pvt_table

Paid             0.0           1.0
Type
Link    20935.875000  12167.833333
Photo   10860.228758  19069.672269
Status  12144.514286  16349.200000
Video   61058.666667  43816.000000

In [60]:
transpose_df = df.head(10).T
transpose_df

,0,1,2,3,4,5,6,7,8,9
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo
Category,2,2,3,2,2,2,3,3,2,3
Post Month,12,12,12,12,12,12,12,12,12,12
Post Weekday,4,3,3,2,2,1,1,7,7,6
Post Hour,3,10,3,10,3,9,3,9,3,10
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199
comment,4,5,0,58,19,1,3,0,0,3
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142

In [61]:
transpose_df.shape

(19, 10)

In [62]:
sort = df.sort_values(by='Lifetime Post Total Reach',ascending=False)

In [63]:
sort

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.000000,6334
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.000000,313
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.000000,176
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.000000,271
380,111620,Photo,1,4,7,14,0.0,128064,251269,1539,1408,2506,84046,32384,985,8,186.0,18.000000,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.000000,6
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,27.266129,2
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.000000,5
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.000000,7
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.000000,2

In [66]:
subset = df[(df['Paid'] == 1) & (df['Lifetime Post Total Reach'] > 5000)]
subset.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713

In [70]:
sortsubset = subset.sort_values(by=['Lifetime Post Total Reach','like'],ascending=[False, False])
sortsubset

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.0,176
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
446,96749,Photo,1,3,1,2,1.0,98816,125026,11452,11328,18115,16682,10336,1356,10,197.0,21.0,228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
385,109670,Photo,3,4,5,7,1.0,5298,8875,657,575,874,5640,3206,471,5,140.0,38.0,183
459,92614,Photo,2,2,2,3,1.0,5290,9100,1053,994,1326,6285,3578,441,2,129.0,32.0,163
412,106928,Photo,1,4,4,3,1.0,5290,8132,612,570,857,6032,3794,454,1,89.0,14.0,104
363,115893,Photo,3,4,4,15,1.0,5212,9035,736,642,1005,6258,3608,597,1,179.0,30.0,210